#!/bin/bash -ex

source hooks/functions.sh

for base in $base_imgs; do
    tag_postfix=$(v2t $base)

    time docker push nobodyxu/intel-mkl:${DOCKER_TAG}-${tag_postfix}
    time docker push nobodyxu/intel-mkl:$(date +%Y)-${tag_postfix}
done
